services:
  db:
    image: postgres:15-alpine
    container_name: smartchain-db
    restart: always
    environment:
      POSTGRES_USER: esg
      POSTGRES_PASSWORD: esg1234
      POSTGRES_DB: smartchain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
